jenkinsci/mask-passwords-plugin

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/passwordparam/PasswordParameterValue.java
This change implements API for sensitive variables, which is required to hide passwords in plugins like EnvInject.
The code is an adjusted copy of <code>makeBuildVariables</code>.
@reviewbybees
> [FIXED JENKINS-25821] - Honor the sensitive variables engine in Mask Passwords

- README.md
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConsoleLogFilter.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsOutputStream.java
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.properties
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/config.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/config.properties
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/global.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/global.properties
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/help-globalVarMaskEnabledGlobally.html
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/help-globalVarMaskRegexes.html
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/help-globalVarPasswordPairs.html
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/help.html
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
This pull request adds two major features to the Mask Passwords plugin:
1. The ability to mask user-defined regular expressions in addition to passwords. This is useful because (a) it doesn't require defining the password explicitly in the configuration and, (b) it supports masking secrets that aren't known ahead of time. Our use case is AWS credentials; the AWS secret key portion of credentials [matches](https://blogs.aws.amazon.com/security/post/Tx1XG3FX6VMU6O5/A-safer-way-to-distribute-AWS-credentials-to-EC2) `(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])`. The previous Mask Passwords implementation caused problems for jobs that use temporary credentials, or that generate their own credentials and echo them in the job's output.
2. The ability to enable the plugin globally. …
> Mask Regexes and Global option

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsOutputStream.java
the logger maybe buffered output stream (other plugin implemented ConsoleLogFilter may add another layer of buffer), need allow caller to flush and close the logger
> Invoke flush() and close() for the logger in MaskPasswordOutputStream

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsOutputStream.java
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsURLEncodingTest.java
This should fix [JENKINS-34908](https://issues.jenkins-ci.org/browse/JENKINS-34908) by trying to mask URL encoded passwords as well
> JENKINS-34908, mask url encoded passwords if necessary

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
- src/main/java/com/michelin/cio/hudson/plugins/passwordparam/PasswordParameterDefinition.java
- src/test/java/com/michelin/cio/hudson/plugins/integrations/CorePasswordParameterTest.java
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordConfigTests.java
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsURLEncodingTest.java
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
- src/test/java/com/michelin/cio/hudson/plugins/passwordparam/PasswordParameterTest.java
Likely the change also solves many other issues reported to the plugin. Still need direct tests for them BTW.
@reviewbybees @bpmarinho @brockoffdev I would appreciate reviews and manual testing
> [JENKINS-25735, JENKINS-41955, etc.] Improve masking of passwords in the plugin

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
There is a bug in the implemetation of the isMasked(String paramValueClassName) method.
Simply put, the paramvalue (Specific class to mask) would never match the class of the getValue() method. For instance when using reflection the CredentialParameterDefinition getDefaultParameterValue() value, we get the return type to be ParameterValue...that is incorrect since the method returns a CredentialsParameterValue, which is the class name we use to check agains 'Credentials'.
> [JENKINS-25735] Credentials can now be masked.

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
Finalizes and enhances the original PR from @MadsNielsen. See #7 
> There is a bug in the implemetation of the isMasked(String paramValueClassName) method.
Simply put, the paramvalue (Specific class to mask) would never match the class of the getValue() method. For instance when using reflection the CredentialParameterDefinition getDefaultParameterValue() value, we get the return type to be ParameterValue...that is incorrect since the method returns a CredentialsParameterValue, which is the class name we use to check agains 'Credentials'.
https://issues.jenkins-ci.org/browse/JENKINS-25735
@reviewbybees
> [JENKINS-25735] Credentials can now be masked

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordConfigTests.java
This is a regression I have introduced in 2.10.
https://issues.jenkins-ci.org/browse/JENKINS-43504
@reviewbybees
> [FIXED JENKINS-43504] - Prevent NullPointerExecption when reading configuraton from disk

- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConsoleLogFilter.java
When enabled globally it should work with all types of Jobs, also pipelines. Depends on JENKINS-45693 or that JENKINS-38381 implements this.
> use modern api in ConsoleLogFilter to allow for pipeline jobs to be filtered globally

- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/global.jelly
Since the security issue has been public for several months, there's no need to hide proposing the fix.
This fixes the global configuration page by displaying the encrypted values of global password variables instead of plaintext within the password form.
See also:
- [SECURITY-157][SECURITY-157] (description unknown to me)
- [security advisory published 2019-08-07][advisory]
[advisory]: https://jenkins.io/security/advisory/2019-08-07/#SECURITY-157
[SECURITY-157]: https://issues.jenkins-ci.org/browse/SECURITY-157
> [SECURITY-157] Fix global mask passwords config

- .gitignore
- pom.xml
- src/main/resources/com/michelin/cio/hudson/plugins/passwordparam/PasswordParameterValue/value.jelly
- src/main/resources/index.jelly
1. Changed plugin description (added information about non-stored password).
2. Edited daring "view build parameters" value "You really think you can access this value?" to "non-stored password parameter".
When I press "see build parameters" I see "You really think you can access this value?". This question is quite daring and it is better to remove or change it. My clients always asks me to remove this question or replace with some other value.
> Removed daring "view build parameters" value

- docs/CHANGELOG.old.md
- docs/README.md
- pom.xml
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConsoleLogFilter.java
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/config.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/config.properties
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/global.jelly
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/help-globalVarMaskEnabledGlobally.html
- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/help.html
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
* Replace Hudson mentions with Jenkins
* Add `@Symbol` to the build wrapper
* Fix config page mess caused by very high ordinal placing it above Jenkins core widgets in system configuration
* Merge sections in system configuration to one, it looked very strange with 3
* Convert tables to divs in form layout, note this heavily used tables for layout and I've dropped compatibility with old core to make this easier to implement, understand and maintain.
* Add bom
* Remove workspace requirement for build wrapper (requires somewhat new core (not sure exact version))
* Correct documentation about pipeline being supported for global setting (it's not)
* Implement data-binding for build wrapper, I haven't updated the `configure` method because this plugin uses a super weird pattern where it's …
> JENKINS-64523 Jenkins core >2.263 fixes

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
Otherwise there is an exception on startup. A better fix would be to actually patch the code to do proper file checks, just a quick patch.
```
java.nio.file.NoSuchFileException: ... com.michelin.cio.hudson.plugins.maskpasswords.MaskPasswordsConfig.xml
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
at java.nio.file.Files.newByteChannel(Files.java:361)
at java.nio.file.Files.newByteChannel(Files.java:407)
at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
at …
```
> Prevent error on startup when config is missing

- pom.xml
Updates to the most recent parent pom and updates to require Java 11 and Jenkins 2.361.4 or newer.
https://stats.jenkins.io/pluginversions/mask-passwords.html shows that 60% of the installations of the most recent release of the plugin were already running at least Jenkins 2.361.1 as of the early January 2023 run of that installation count report.  Since a majority of users of the current version are already on Jenkins 2.361.1 or newer, let's modernize the plugin to require Java 11 and Jenkins 2.361.4 or newer.
https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ recommends either 2.361.4 or 2.346.3 as minimum required version.  By choosing 2.361.4, the plugin moves from Java 8 to Java 11.
This would be good to combine with #29 for another release of the …
> Require Jenkins 2.361.4 or newer

- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
Temporary files cause meaningless test failures
> Skip two assertions on Windows

- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
- src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConsoleLogFilter.java
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
If you try to create a Maskpassword Pipiline using regex, a class cast exception will occur.
DataBoundConstructor uses String and String as parameters, but in Descriptor, it is sent by casting to VarMaskRegex.
If I change the descriptor to properly use VarMaskRegexEntry, it works fine.
Pipeline Script
Console Log Output
```[tasklist]
```
> [JENKINS-68885] Fix class cast exception when VarMaskRegexEntry data is not bound

- .github/dependabot.yml
- pom.xml
The Jenkins plugin archetype uses jenkins.baseline to prevent inconsistencies between the minimum required Jenkins version and the Jenkins plugin bill of materials version.  Use the same technique in this plugin.
Confirmed that compilation passes.  Will rely on ci.jenkins.io to check automated tests.  Behavior preserving transformation.
> Use jenkins.baseline to match plugin archetype

- pom.xml
- src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
See https://github.com/jenkinsci/bom/pull/5046 for context.
It seems like `MaskPasswordsWorkflowTest#basics` and `MaskPasswordsWorkflowTest#basicsRegex` are being flaky on slow filesystems. 
If accepted, this change must be released in order to resolve https://github.com/jenkinsci/bom/issues/4781
Since I cannot reproduce the error _naturally_ I manually added a `atomic12345.tmp` file containing `s3cr3t` to check if the workaround behaves as intented.
> Add workaround for flaky tests

- src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/config.jelly
The hard coded color make it impossible to read the text with dark theme
Before:
After:
> Use jenkins-alert-warning instead of a hard coded color

- pom.xml
Declare dependencies explicitly so that dependency updates do not inadvertently bundle a new dependency in the plugin.
Ban JUnit 4 tests because the tests in the plugin have all been converted to JUnit 5.
Confirmed that the plugin compiles and passes automated tests.
> Declare dependencies and ban JUnit 4 tests
